# things used for colour palettes and legends etc.

# baseline data attributes
baseline_vals <- c("Arable and Horticulture ALC Grade 1",
                   "Arable and Horticulture ALC Grade 2",
                   "Arable and Horticulture ALC Grade 3a",
                   "Arable and Horticulture ALC Grade 3b",
                   "Arable and Horticulture ALC Grade 4",
                   "Arable and Horticulture ALC Grade 5",
                   "Improved Grassland ALC Grade 1",
                   "Improved Grassland ALC Grade 2",
                   "Improved Grassland ALC Grade 3a",
                   "Improved Grassland ALC Grade 3b",
                   "Improved Grassland ALC Grade 4",
                   "Improved Grassland ALC Grade 5",
                   "Semi Natural Grassland BMV",
                   "Semi Natural Grassland Non-BMV",
                   "Mountain, Heath and Bog BMV",
                   "Mountain, Heath and Bog Non-BMV",
                   "Broadleaf Woodland",
                   "Coniferous Woodland",
                   "Water",
                   "Coastal",
                   "Urban"
)

legend_baseline_pal <- c("#FEE391",
                         "#FEC44F",
                         "#FE9929",
                         "#EC7014",
                         "#CC4C02",
                         "#8C2D04",
                         "#CCECE6",
                         "#99D8C9",
                         "#66C2A4",
                         "#41AE76",
                         "#238B45",
                         "#005824",
                         "#A1DAB4",
                         "#41B6C4",
                         "#FA9FB5",
                         "#C51B8A",
                         "#FF0000",
                         "#7DFC00",
                         "#1F8EFF",
                         "#FFE3B3",
                         "#000000")

data_baseline_pal <- c("#FEE391",
                       "#FEC44F",
                       "#FE9929",
                       "#EC7014",
                       "#CC4C02",
                       "#8C2D04",
                       "#CCECE6",
                       "#99D8C9",
                       "#66C2A4",
                       "#41AE76",
                       "#238B45",
                       "#005824",
                       "#A1DAB4",
                       "#41B6C4",
                       "#FA9FB5",
                       "#C51B8A",
                       "#FF0000",
                       "#7DFC00",
                       "#1F8EFF",
                       "#FFE3B3",
                       "#000000")